version: "3"

services:
  prism:
    image: stoplight/prism:4
    command: proxy -h 0.0.0.0 /schema/api.yml http://api-server:3000
    ports:
      - 4010:4010
    volumes:
      - ./sos21-api-server/schema:/schema
    depends_on:
      - api-server
  api-server:
    image: docker.pkg.github.com/sohosai/sos21-backend/sos21-backend
    command: sos21-api-server
    environment:
      SOS21_API_SERVER_JWT_AUDIENCE: ${SOS21_FIREBASE_PROJECT_ID:?}
      SOS21_API_SERVER_JWT_ISSUER: "https://securetoken.google.com/${SOS21_FIREBASE_PROJECT_ID:?}"
      SOS21_API_SERVER_JWT_KEYS_URL: "https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com"
      SOS21_API_SERVER_POSTGRES_URI: "postgres://sos21:sos21@db:5432/sos21"
      SOS21_API_SERVER_BIND: "0.0.0.0:3000"
    ports:
      - 3000:3000
    depends_on:
      - db
      - run-migrations
  run-migrations:
    image: docker.pkg.github.com/sohosai/sos21-backend/sos21-backend
    command: sos21-run-migrations --wait
    environment:
      SOS21_RUN_MIGRATIONS_POSTGRES_URI: "postgres://sos21:sos21@db:5432/sos21"
    depends_on:
      - db
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: sos21
      POSTGRES_USER: sos21
      POSTGRES_DB: sos21
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
