version: "3"

services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    ports:
      - ${POSTGRES_PORT:?}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
