version: "3"

services:
  prism:
    image: stoplight/prism:4
    command: proxy /schema/api.yml http://${SOS21_API_SERVER_BIND:?} --errors
    volumes:
      - ./sos21-api-server/schema:/schema
    network_mode: host
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    ports:
      - ${POSTGRES_PORT:?}:5432
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data

volumes:
  postgres-data-dev:
