[package]
name = "sos21-use-case"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
tracing = "0.1"
tracing-futures = "0.2"
sos21-model = { path = "../sos21-model" }
sos21-context = { path = "../sos21-context" }
