[package]
name = "sos21-gateway-database"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
futures = "0.3"
async-trait = "0.1.42"
sos21-database = { path = "../../sos21-database" }
sos21-domain-model = { path = "../../sos21-domain/model" }
sos21-domain-context = { path = "../../sos21-domain/context" }
sqlx = { git = "https://github.com/launchbadge/sqlx", features = ["postgres"] }
