[package]
name = "sos21-database"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
edition = "2018"

[dependencies]
sqlx = { git = "https://github.com/launchbadge/sqlx", features = ["macros", "postgres", "chrono", "runtime-tokio-rustls"] }
anyhow = "1"
chrono = "0.4"
