[package]
name = "sos21-context"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
edition = "2018"

[dependencies]
sos21-model = { path = "../sos21-model" }
async-trait = "0.1.42"
anyhow = "1"
chrono = "0.4"
