[package]
name = "sos21-domain-context"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
edition = "2018"

[dependencies]
sos21-domain-model = { path = "../model" }
async-trait = "0.1.42"
anyhow = "1"
thiserror = "1"
