on:
  schedule:
    - cron: '0 0 * * *'

name: Audit

jobs:
  audit:
    name: Security audit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: sos-backend
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN_JSYS23 }}"
      # workaround for actions-rs/audit-check#163
      - run: nix-env -if ./nix/ignore-generate-lockfile-cargo.nix
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
