on:
  schedule:
    - cron: '0 0 * * *'

name: Audit

jobs:
  audit:
    name: Security audit
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: sos21-backend
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      # workaround for actions-rs/audit-check#163
      - run: nix-env -if ./nix/ignore-generate-lockfile-cargo.nix
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
