on: [push, pull_request]

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: sos21-backend
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
  build-shell:
    name: Build shell
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: sos21-backend
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build shell.nix -A nativeBuildInputs
  fmt:
    name: Rustfmt
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: sos21-backend
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-env -f ./nix/pkgs.nix -iA rustPlatform.rust.cargo
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: sos21-backend
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-env -f ./nix/pkgs.nix -iA rustPlatform.rust.cargo
      - uses: actions-rs/clippy-check@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          args: -- -D warnings
  lint-api-schema:
    name: Lint OpenAPI schema
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - run: nix-env -f ./nix/pkgs.nix -iA nodejs
      - run: cd sos21-api-server/schema; npm install
      - run: cd sos21-api-server/schema; npm run lint
