on:
  push:
    branches:
      - develop

name: Generate documentation

jobs:
  api-server:
    name: Generate documentation from OpenAPI schema
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: nix-env -f ./nix/pkgs.nix -iA nodejs
      - run: cd sos21-api-server/schema; npm install
      - run: cd sos21-api-server/schema; npm run build:doc -- --output dist/api-server.html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sos21-api-server/schema/dist
          destination_dir: develop
          keep_files: true
  rustdoc:
    name: Generate rustdoc documentation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: sos-backend
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN_JSYS23 }}'
      - run: nix-env -f ./nix/pkgs.nix -iA rustPlatform.rust.cargo
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --document-private-items
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          destination_dir: develop
          keep_files: true
